export const styleData = [
  { type: "input-number", key: "left", label: "x 坐标" },
  { type: "input-number", key: "top", label: "y 坐标" },
  { type: "input-number", key: "rotate", label: "旋转角度" },
  { type: "input-number", key: "width", label: "宽" },
  { type: "input-number", key: "height", label: "高" },
  { type: "color-picker", key: "color", label: "颜色" },
  { type: "color-picker", key: "backgroundColor", label: "背景色" },
  { type: "", key: "borderWidth", label: "边框宽度" },
  { type: "", key: "borderStyle", label: "边框风格" },
  { type: "color-picker", key: "borderColor", label: "边框颜色" },
  { type: "", key: "borderRadius", label: "边框半径" },
  { type: "", key: "fontSize", label: "字体大小" },
  { type: "", key: "fontWeight", label: "字体粗细" },
  { type: "", key: "lineHeight", label: "行高" },
  { type: "", key: "letterSpacing", label: "字间距" },
  { type: "", key: "textAlign", label: "左右对齐" },
  { type: "", key: "verticalAlign", label: "上下对齐" },
  { type: "", key: "opacity", label: "不透明度" }
];
